# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-scales-mariner"
BBFILE_PATTERN_meta-scales-mariner = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-scales-mariner = "6"

LAYERDEPENDS_meta-scales-mariner = "core"
LAYERSERIES_COMPAT_meta-scales-mariner = "scarthgap"
