# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-scales-layer"
BBFILE_PATTERN_meta-scales-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-scales-layer = "999"

LAYERDEPENDS_meta-scales-layer = "core"
LAYERSERIES_COMPAT_meta-scales-layer = "scarthgap"
