FILESEXTRAPATHS:prepend := "${THISDIR}/files:"
SRC_URI += "file://0001-makefile-and-dts-mariner-1b.patch"
COMPATIBLE_MACHINE  = "^("
COMPATIBLE_MACHINE .= "scales-mariner-1"
COMPATIBLE_MACHINE .= ")$"
